remote_theme: "mmistakes/minimal-mistakes@4.13.0"

logo: "assets/images/SKAT_logo.png"

title: "Storm King Adventure Tours"


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      sidebar:
        nav: "docs"


include: ["_pages"]