remote_theme: "mmistakes/minimal-mistakes@4.13.0"


title: "Storm King Adventure Tours"
logo: "/assets/images/SKAT_logo.png"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"


include: ["_pages"]